### ISSUE TITLE
Zoom avec hotspots

### ISSUE THREAD

**Issue by Speuta** [fabsharp/Zoomable#2]
Faire en sorte que si sur le départ de la gesture pinch, on appuie avec un doigt sur un autre élément à l’intérieur du container, ça zoom quand même (wrapper ?).

**Comment by fabsharp** [comment]
Done, après la MAJ de dist, il y'a juste un changement dans demo/unzoomable.hotspots/ImageMap.js, ligne 36 https://github.com/fabsharp/Zoomable/blame/1f69e49e7d4bb70482a0874720f80119dadd9bba/demo/unzoomable.hotspots/ImageMap.js
